name: Windows
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          choco install cmake
      - name: Configure
        shell: bash
        run: |
          mkdir build
          cmake -B build --preset="debug"
      - name: Build
        shell: bash
        run: cmake --build build --config Debug
      - name: Test
        shell: bash
        run: |
          cp -r tests/assets build/tests
          cd build
          ctest -V